import create from "zustand";
import faker from "@faker-js/faker";
import { sub } from "date-fns";

const NOTIFICATIONS = [
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=3",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=1",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=7",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=4",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=5",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=3",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=1",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=7",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=4",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=5",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=3",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=1",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=7",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=4",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
  {
    id: faker.datatype.uuid(),
    title: faker.name.findName(),
    description: "te mando un mensaje",
    avatar: "https://i.pravatar.cc/300?img=5",
    type: "chat_message",
    createdAt: sub(new Date(), { hours: 3, minutes: 30 }),
    isReaded: false,
  },
];

export const useChatStore = create(() => ({
  notifactions: NOTIFICATIONS,
}));

export const chatStoreSelector = (state) => ({
  notifactions: state.notifactions,
});
